export const SET_NEON_ENABLED = 'SET_NEON_ENABLED';
export const SET_NEON_SPEAKING = 'SET_NEON_SPEAKING';

export const SET_VOICE_TRANSMIT_RESULT = 'SET_VOICE_TRANSMIT_RESULT';

export const SET_MUSIC_PLAYER = 'SET_MUSIC_PLAYER'